sudo: false

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 6
  - 4
  - 0.12

notifications:
  email: false

before_script:
  - npm prune
  - curl -Lo travis_after_all.py https://git.io/vLSON

after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
