language: node_js
services:
- docker
cache:
  directories:
  - $HOME/.npm
notifications:
  email: false
node_js: 7
before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: npm run deploy
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
